version: '3'
services:
  db:
    image: mysql:5.7.24
    environment:
      MYSQL_DATABASE: "ChatSys_development"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      REDIS_LOCALHOST: "redis"
      RABBITMQ_HOSTNAME: "rabbitmq"
      MYSQL_HOSTNAME: "db"